### ISSUE TITLE
This is learn how auto close issue 

### ISSUE THREAD

**Issue by foxhsiao** [degather/bootcamp#10]
@jilingchiu try auto close this issue for your pull request in ID #8 :)

Referance document : [closing-issues-via-commit-messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by jilingchiu** [comment]
完成 close

**Comment by foxhsiao** [comment]
@jilingchiu try auto close this issue for your pull request not use `manually`, you can see yesterday training pull request : #6 

Referance document : [closing-issues-via-commit-messages](https://help.github.com/articles/closing-issues-via-commit-messages/)

**Comment by jilingchiu** [comment]
test

**Comment by jilingchiu** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;CYbYtB03&#x2F;28-share-github"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> [share] Github 版本管理團隊協作</a>
